name: CI Gaming

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Install k6
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg2 curl
        curl -s https://packagecloud.io/install/repositories/loadimpact/k6/script.deb.sh | sudo bash
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Run performance tests
      run: npm run k6